# Generated by Django 5.0.4 on 2024-04-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_weatherdatahourly"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdatahourly",
            name="cloud_cover_percentage",
        ),
    ]
